version: '3.9'

services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rent
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}